# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tygate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tygate

  
pod 'IQKeyboardManagerSwift'

pod 'Alamofire'

pod 'Toast-Swift'

pod 'SwiftyJSON'

pod 'SDWebImage'

 pod 'SJSegmentedScrollView'
  

end
